name: image-builder
'on':
  push:
    paths:
      - images-current.yml
      - .github/workflows/image-builder.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: 'build jpegxl:latest'
        run: 'docker build -t aburgess/jpegxl:latest -f jpegxl.latest.Dockerfile .'
      - name: 'push jpegxl:latest'
        run: 'docker push aburgess/jpegxl:latest'
