name: image-builder

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: login to docker
      run: docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}