name: image-builder
'on':
  push:
    paths:
      - images-current.yml
      - .github/workflows/image-builder.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: 'build docker:latest'
        run: 'docker build -t aburgess/docker:latest -f docker.latest.Dockerfile .'
      - name: 'build node:latest'
        run: 'docker build -t aburgess/node:latest -f node.latest.Dockerfile .'
      - name: 'build node:extra'
        run: 'docker build -t aburgess/node:extra -f node.extra.Dockerfile .'
      - name: 'push docker:latest node:latest node:extra'
        run: |-
          docker push aburgess/docker:latest
          docker push aburgess/node:latest
          docker push aburgess/node:extra
