name: image-builder
'on':
  push:
    paths:
      - images-current.yml
      - .github/workflows/image-builder.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: 'build gcc:latest'
        run: 'docker build -t aburgess/gcc:latest -f gcc.latest.Dockerfile .'
      - name: 'build gcc:extra'
        run: 'docker build -t aburgess/gcc:extra -f gcc.extra.Dockerfile .'
      - name: 'build node:latest'
        run: 'docker build -t aburgess/node:latest -f node.latest.Dockerfile .'
      - name: 'build node:extra'
        run: 'docker build -t aburgess/node:extra -f node.extra.Dockerfile .'
      - name: 'build node:lts'
        run: 'docker build -t aburgess/node:lts -f node.lts.Dockerfile .'
      - name: 'push gcc:latest gcc:extra node:latest node:extra node:lts'
        run: |-
          docker push aburgess/gcc:latest
          docker push aburgess/gcc:extra
          docker push aburgess/node:latest
          docker push aburgess/node:extra
          docker push aburgess/node:lts
