name: image-builder

on:
  push:
    paths:
    - 'images-current.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: no-op
      run: echo nothing to run
