name: image-builder
'on':
  push:
    paths:
      - images-current.yml
      - .github/workflows/image-builder.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: 'build node:extra'
        run: 'docker build -t aburgess/node:extra -f node.extra.Dockerfile .'
      - name: 'build node:lts'
        run: 'docker build -t aburgess/node:lts -f node.lts.Dockerfile .'
      - name: 'push node:extra node:lts'
        run: |-
          docker push aburgess/node:extra
          docker push aburgess/node:lts
