name: image-builder

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: get docker 
      run: docker version && docker-compose version
