name: image-builder
'on':
  push:
    paths:
      - images-current.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: 'build binaries:mo'
        run: 'docker build -t aburgess/binaries:mo .'
      - name: 'build common:latest'
        run: 'docker build -t aburgess/common:latest .'
      - name: 'build common:extra'
        run: 'docker build -t aburgess/common:extra .'
      - name: 'build docker:latest'
        run: 'docker build -t aburgess/docker:latest .'
      - name: 'build gcc:latest'
        run: 'docker build -t aburgess/gcc:latest .'
      - name: 'build gcc:extra'
        run: 'docker build -t aburgess/gcc:extra .'
      - name: 'build node:latest'
        run: 'docker build -t aburgess/node:latest .'
      - name: 'build node:extra'
        run: 'docker build -t aburgess/node:extra .'
      - name: 'build node:lts'
        run: 'docker build -t aburgess/node:lts .'
      - name: >-
          push binaries:mo common:latest common:extra docker:latest gcc:latest
          gcc:extra node:latest node:extra node:lts
        run: |-
          docker push aburgess/binaries:mo
          docker push aburgess/common:latest
          docker push aburgess/common:extra
          docker push aburgess/docker:latest
          docker push aburgess/gcc:latest
          docker push aburgess/gcc:extra
          docker push aburgess/node:latest
          docker push aburgess/node:extra
          docker push aburgess/node:lts
