name: makefile-builder
on:
  push:
    paths-ignore:
      - netlify
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: 'docker login -u aburgess -p ${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: restore Makefile cache
        uses: actions/cache@v2
        with:
          path: |
            builder
          key: ${{ runner.os }}-${{ hashFiles('images.yml') }}
      - name: Create builder if not exists
        run: mkdir -p builder
      - name: Fetch Makefile
        run: curl --data-binary "@images.yml" https://adamburgess-image-builder.netlify.app/.netlify/functions/makefile > builder/Makefile
      - name: Build packages
        working-directory: builder
        run: make all
