name: scheduler

on:
  push:
    branches:
      - master
    paths-ignore:
    - 'images-current.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: scheduler
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: install node modules
        run: yarn
      - name: run scheduler
        run: yarn start
